
package com.kgonzaga.soap_client.app.persistence.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://kgonzaga.com/soap/employee-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param createEmployeeRequest
     * @return
     *     returns com.kgonzaga.soap_client.app.persistence.wsdl.CreateEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "createEmployeeResponse", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "createEmployeeResponse")
    public CreateEmployeeResponse createEmployee(
        @WebParam(name = "createEmployeeRequest", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "createEmployeeRequest")
        CreateEmployeeRequest createEmployeeRequest);

    /**
     * 
     * @param updateEmployeeRequest
     * @return
     *     returns com.kgonzaga.soap_client.app.persistence.wsdl.UpdateEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "updateEmployeeResponse", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "updateEmployeeResponse")
    public UpdateEmployeeResponse updateEmployee(
        @WebParam(name = "updateEmployeeRequest", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "updateEmployeeRequest")
        UpdateEmployeeRequest updateEmployeeRequest);

    /**
     * 
     * @param getEmployeeRequest
     * @return
     *     returns com.kgonzaga.soap_client.app.persistence.wsdl.GetEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "getEmployeeResponse", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "getEmployeeResponse")
    public GetEmployeeResponse getEmployee(
        @WebParam(name = "getEmployeeRequest", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "getEmployeeRequest")
        GetEmployeeRequest getEmployeeRequest);

    /**
     * 
     * @param getAllEmployeesRequest
     * @return
     *     returns com.kgonzaga.soap_client.app.persistence.wsdl.GetAllEmployeesResponse
     */
    @WebMethod
    @WebResult(name = "getAllEmployeesResponse", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "getAllEmployeesResponse")
    public GetAllEmployeesResponse getAllEmployees(
        @WebParam(name = "getAllEmployeesRequest", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "getAllEmployeesRequest")
        GetAllEmployeesRequest getAllEmployeesRequest);

    /**
     * 
     * @param deleteEmployeeRequest
     * @return
     *     returns com.kgonzaga.soap_client.app.persistence.wsdl.DeleteEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "deleteEmployeeResponse", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "deleteEmployeeResponse")
    public DeleteEmployeeResponse deleteEmployee(
        @WebParam(name = "deleteEmployeeRequest", targetNamespace = "http://kgonzaga.com/soap/employee-web-service", partName = "deleteEmployeeRequest")
        DeleteEmployeeRequest deleteEmployeeRequest);

}
